// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: lifecycle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lifecycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BucketSlug    string                 `protobuf:"bytes,2,opt,name=bucket_slug,json=bucketSlug,proto3" json:"bucket_slug,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lifecycle) Reset() {
	*x = Lifecycle{}
	mi := &file_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifecycle) ProtoMessage() {}

func (x *Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifecycle.ProtoReflect.Descriptor instead.
func (*Lifecycle) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *Lifecycle) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lifecycle) GetBucketSlug() string {
	if x != nil {
		return x.BucketSlug
	}
	return ""
}

func (x *Lifecycle) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Lifecycle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lifecycle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PostLifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketSlug    string                 `protobuf:"bytes,1,opt,name=bucket_slug,json=bucketSlug,proto3" json:"bucket_slug,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLifecycleRequest) Reset() {
	*x = PostLifecycleRequest{}
	mi := &file_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLifecycleRequest) ProtoMessage() {}

func (x *PostLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLifecycleRequest.ProtoReflect.Descriptor instead.
func (*PostLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *PostLifecycleRequest) GetBucketSlug() string {
	if x != nil {
		return x.BucketSlug
	}
	return ""
}

func (x *PostLifecycleRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type PostLifecycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifecycle     *Lifecycle             `protobuf:"bytes,1,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLifecycleResponse) Reset() {
	*x = PostLifecycleResponse{}
	mi := &file_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLifecycleResponse) ProtoMessage() {}

func (x *PostLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLifecycleResponse.ProtoReflect.Descriptor instead.
func (*PostLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *PostLifecycleResponse) GetLifecycle() *Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

type GetLifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketSlug    string                 `protobuf:"bytes,1,opt,name=bucket_slug,json=bucketSlug,proto3" json:"bucket_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLifecycleRequest) Reset() {
	*x = GetLifecycleRequest{}
	mi := &file_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLifecycleRequest) ProtoMessage() {}

func (x *GetLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLifecycleRequest.ProtoReflect.Descriptor instead.
func (*GetLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *GetLifecycleRequest) GetBucketSlug() string {
	if x != nil {
		return x.BucketSlug
	}
	return ""
}

type GetLifecycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifecycle     *Lifecycle             `protobuf:"bytes,1,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLifecycleResponse) Reset() {
	*x = GetLifecycleResponse{}
	mi := &file_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLifecycleResponse) ProtoMessage() {}

func (x *GetLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLifecycleResponse.ProtoReflect.Descriptor instead.
func (*GetLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *GetLifecycleResponse) GetLifecycle() *Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

type DeleteLifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketSlug    string                 `protobuf:"bytes,1,opt,name=bucket_slug,json=bucketSlug,proto3" json:"bucket_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLifecycleRequest) Reset() {
	*x = DeleteLifecycleRequest{}
	mi := &file_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLifecycleRequest) ProtoMessage() {}

func (x *DeleteLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLifecycleRequest.ProtoReflect.Descriptor instead.
func (*DeleteLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLifecycleRequest) GetBucketSlug() string {
	if x != nil {
		return x.BucketSlug
	}
	return ""
}

type DeleteLifecycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLifecycleResponse) Reset() {
	*x = DeleteLifecycleResponse{}
	mi := &file_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLifecycleResponse) ProtoMessage() {}

func (x *DeleteLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLifecycleResponse.ProtoReflect.Descriptor instead.
func (*DeleteLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLifecycleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_lifecycle_proto protoreflect.FileDescriptor

const file_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x0flifecycle.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n" +
	"\tLifecycle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vbucket_slug\x18\x02 \x01(\tR\n" +
	"bucketSlug\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\x14PostLifecycleRequest\x12\x1f\n" +
	"\vbucket_slug\x18\x01 \x01(\tR\n" +
	"bucketSlug\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"D\n" +
	"\x15PostLifecycleResponse\x12+\n" +
	"\tlifecycle\x18\x01 \x01(\v2\r.pb.LifecycleR\tlifecycle\"6\n" +
	"\x13GetLifecycleRequest\x12\x1f\n" +
	"\vbucket_slug\x18\x01 \x01(\tR\n" +
	"bucketSlug\"C\n" +
	"\x14GetLifecycleResponse\x12+\n" +
	"\tlifecycle\x18\x01 \x01(\v2\r.pb.LifecycleR\tlifecycle\"9\n" +
	"\x16DeleteLifecycleRequest\x12\x1f\n" +
	"\vbucket_slug\x18\x01 \x01(\tR\n" +
	"bucketSlug\"3\n" +
	"\x17DeleteLifecycleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe7\x01\n" +
	"\x10LifecycleService\x12D\n" +
	"\rPostLifecycle\x12\x18.pb.PostLifecycleRequest\x1a\x19.pb.PostLifecycleResponse\x12A\n" +
	"\fGetLifecycle\x12\x17.pb.GetLifecycleRequest\x1a\x18.pb.GetLifecycleResponse\x12J\n" +
	"\x0fDeleteLifecycle\x12\x1a.pb.DeleteLifecycleRequest\x1a\x1b.pb.DeleteLifecycleResponseB.Z,github.com/cthulhu-platform/lifecycle/pkg/pbb\x06proto3"

var (
	file_lifecycle_proto_rawDescOnce sync.Once
	file_lifecycle_proto_rawDescData []byte
)

func file_lifecycle_proto_rawDescGZIP() []byte {
	file_lifecycle_proto_rawDescOnce.Do(func() {
		file_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lifecycle_proto_rawDesc), len(file_lifecycle_proto_rawDesc)))
	})
	return file_lifecycle_proto_rawDescData
}

var file_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lifecycle_proto_goTypes = []any{
	(*Lifecycle)(nil),               // 0: pb.Lifecycle
	(*PostLifecycleRequest)(nil),    // 1: pb.PostLifecycleRequest
	(*PostLifecycleResponse)(nil),   // 2: pb.PostLifecycleResponse
	(*GetLifecycleRequest)(nil),     // 3: pb.GetLifecycleRequest
	(*GetLifecycleResponse)(nil),    // 4: pb.GetLifecycleResponse
	(*DeleteLifecycleRequest)(nil),  // 5: pb.DeleteLifecycleRequest
	(*DeleteLifecycleResponse)(nil), // 6: pb.DeleteLifecycleResponse
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_lifecycle_proto_depIdxs = []int32{
	7, // 0: pb.Lifecycle.expires_at:type_name -> google.protobuf.Timestamp
	7, // 1: pb.Lifecycle.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: pb.Lifecycle.updated_at:type_name -> google.protobuf.Timestamp
	7, // 3: pb.PostLifecycleRequest.expires_at:type_name -> google.protobuf.Timestamp
	0, // 4: pb.PostLifecycleResponse.lifecycle:type_name -> pb.Lifecycle
	0, // 5: pb.GetLifecycleResponse.lifecycle:type_name -> pb.Lifecycle
	1, // 6: pb.LifecycleService.PostLifecycle:input_type -> pb.PostLifecycleRequest
	3, // 7: pb.LifecycleService.GetLifecycle:input_type -> pb.GetLifecycleRequest
	5, // 8: pb.LifecycleService.DeleteLifecycle:input_type -> pb.DeleteLifecycleRequest
	2, // 9: pb.LifecycleService.PostLifecycle:output_type -> pb.PostLifecycleResponse
	4, // 10: pb.LifecycleService.GetLifecycle:output_type -> pb.GetLifecycleResponse
	6, // 11: pb.LifecycleService.DeleteLifecycle:output_type -> pb.DeleteLifecycleResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_lifecycle_proto_init() }
func file_lifecycle_proto_init() {
	if File_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lifecycle_proto_rawDesc), len(file_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lifecycle_proto_goTypes,
		DependencyIndexes: file_lifecycle_proto_depIdxs,
		MessageInfos:      file_lifecycle_proto_msgTypes,
	}.Build()
	File_lifecycle_proto = out.File
	file_lifecycle_proto_goTypes = nil
	file_lifecycle_proto_depIdxs = nil
}
