// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: lifecycle.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LifecycleService_PostLifecycle_FullMethodName   = "/pb.LifecycleService/PostLifecycle"
	LifecycleService_GetLifecycle_FullMethodName    = "/pb.LifecycleService/GetLifecycle"
	LifecycleService_DeleteLifecycle_FullMethodName = "/pb.LifecycleService/DeleteLifecycle"
)

// LifecycleServiceClient is the client API for LifecycleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LifecycleServiceClient interface {
	PostLifecycle(ctx context.Context, in *PostLifecycleRequest, opts ...grpc.CallOption) (*PostLifecycleResponse, error)
	GetLifecycle(ctx context.Context, in *GetLifecycleRequest, opts ...grpc.CallOption) (*GetLifecycleResponse, error)
	DeleteLifecycle(ctx context.Context, in *DeleteLifecycleRequest, opts ...grpc.CallOption) (*DeleteLifecycleResponse, error)
}

type lifecycleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLifecycleServiceClient(cc grpc.ClientConnInterface) LifecycleServiceClient {
	return &lifecycleServiceClient{cc}
}

func (c *lifecycleServiceClient) PostLifecycle(ctx context.Context, in *PostLifecycleRequest, opts ...grpc.CallOption) (*PostLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostLifecycleResponse)
	err := c.cc.Invoke(ctx, LifecycleService_PostLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleServiceClient) GetLifecycle(ctx context.Context, in *GetLifecycleRequest, opts ...grpc.CallOption) (*GetLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLifecycleResponse)
	err := c.cc.Invoke(ctx, LifecycleService_GetLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lifecycleServiceClient) DeleteLifecycle(ctx context.Context, in *DeleteLifecycleRequest, opts ...grpc.CallOption) (*DeleteLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLifecycleResponse)
	err := c.cc.Invoke(ctx, LifecycleService_DeleteLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifecycleServiceServer is the server API for LifecycleService service.
// All implementations must embed UnimplementedLifecycleServiceServer
// for forward compatibility.
type LifecycleServiceServer interface {
	PostLifecycle(context.Context, *PostLifecycleRequest) (*PostLifecycleResponse, error)
	GetLifecycle(context.Context, *GetLifecycleRequest) (*GetLifecycleResponse, error)
	DeleteLifecycle(context.Context, *DeleteLifecycleRequest) (*DeleteLifecycleResponse, error)
	mustEmbedUnimplementedLifecycleServiceServer()
}

// UnimplementedLifecycleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifecycleServiceServer struct{}

func (UnimplementedLifecycleServiceServer) PostLifecycle(context.Context, *PostLifecycleRequest) (*PostLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostLifecycle not implemented")
}
func (UnimplementedLifecycleServiceServer) GetLifecycle(context.Context, *GetLifecycleRequest) (*GetLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLifecycle not implemented")
}
func (UnimplementedLifecycleServiceServer) DeleteLifecycle(context.Context, *DeleteLifecycleRequest) (*DeleteLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLifecycle not implemented")
}
func (UnimplementedLifecycleServiceServer) mustEmbedUnimplementedLifecycleServiceServer() {}
func (UnimplementedLifecycleServiceServer) testEmbeddedByValue()                          {}

// UnsafeLifecycleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifecycleServiceServer will
// result in compilation errors.
type UnsafeLifecycleServiceServer interface {
	mustEmbedUnimplementedLifecycleServiceServer()
}

func RegisterLifecycleServiceServer(s grpc.ServiceRegistrar, srv LifecycleServiceServer) {
	// If the following call panics, it indicates UnimplementedLifecycleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LifecycleService_ServiceDesc, srv)
}

func _LifecycleService_PostLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).PostLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_PostLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).PostLifecycle(ctx, req.(*PostLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifecycleService_GetLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).GetLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_GetLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).GetLifecycle(ctx, req.(*GetLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LifecycleService_DeleteLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifecycleServiceServer).DeleteLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifecycleService_DeleteLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifecycleServiceServer).DeleteLifecycle(ctx, req.(*DeleteLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LifecycleService_ServiceDesc is the grpc.ServiceDesc for LifecycleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifecycleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LifecycleService",
	HandlerType: (*LifecycleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostLifecycle",
			Handler:    _LifecycleService_PostLifecycle_Handler,
		},
		{
			MethodName: "GetLifecycle",
			Handler:    _LifecycleService_GetLifecycle_Handler,
		},
		{
			MethodName: "DeleteLifecycle",
			Handler:    _LifecycleService_DeleteLifecycle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lifecycle.proto",
}
